export const DataMusic = [
  {
    id: 1,
    Band: "Queen",
    Song: "Bohemian Rhapsody",
    Audio: "MusicFolder/Queen-Bohemian.mp3",
    Image: "src/assets/bohemian.jpg",
  },
  {
    id: 2,
    Band: "Oasis",
    Song: "Whatever",
    Audio: "MusicFolder/Oasis-Whatever.mp3",
    Image: "src/assets/oasis.jpg",
  },
  {
    id: 3,
    Band: "Khalid",
    Song: "Young Dumb",
    Audio: "MusicFolder/Khalid-Young-dumb.mp3",
    Image: "src/assets/young.jpg",
  },
  {
    id: 4,
    Band: "John Lennon",
    Song: "Imagine",
    Audio: "MusicFolder/JohnLennon-Imagine.mp3",
    Image: "src/assets/john.jpg",
  },
  {
    id: 5,
    Band: "Fourtwnty",
    Song: "Realita",
    Audio: "MusicFolder/Fourtwnty-Realita.mp3",
    Image: "src/assets/fourtwnty.jpg",
  },
  {
    id: 6,
    Band: "Sheila on 7",
    Song: "Film Favorit",
    Audio: "MusicFolder/SheilaOn7-Film-Favorite.mp3",
    Image: "src/assets/sheila.jpg",
  },
  {
    id: 7,
    Band: "Katy Perry",
    Song: "Firework",
    Audio: "MusicFolder/KattyPerry-FireWork.mp3",
    Image: "src/assets/katty.jpg",
  },
  {
    id: 8,
    Band: "Coldplay",
    Song: "Fix You",
    Audio: "MusicFolder/Coldplay-Fixyou.mp3",
    Image: "src/assets/coldplay.jpg",
  },
  {
    id: 9,
    Band: "Tipe X",
    Song: "Salam Rindu",
    Audio: "MusicFolder/TipeX-SalamRindu.mp3",
    Image: "src/assets/tipex.jpg",
  },
  {
    id: 10,
    Band: "Dewa 19",
    Song: "Kamulah Satu Satunya",
    Audio: "MusicFolder/Dewa19-Kamulah.mp3",
    Image: "src/assets/dewa19.jpg",
  },
];
